### PR TITLE
Switched request library to axios and various fixes and tests

### LINKED ISSUE #330: Question: Send custom metadata
Loving this library and using it I was able to achieve what I was trying to do. There's however something I can't figure out is how to send custom metadata (title, artist, cover, ...) ?

I understand the `play()` methods accepts and object with a `meta` key however I can't figure out the format I need to send this information for Sonos to parse it.

Is it even possible without using an actual "service" ?

Thanks !

PS : I know it could be done using ID3 tags but I can't edit them in my case

### LINKED ISSUE #413: AlarmClock.prototype.PatchAlarm does not support multiple players
When trying to manage an alarm (e.g disable/enable) through alarmService.SetAlarm error is being raised telling that ID cannot be found. The error is raised in patchAlarm function located in /lib/services/AlarmClock.js

## Expected Behavior
It should be possible to manage alarms even in a multiroom speaker setup

## Current Behavior
Error message "Alarm with id <ID> not found" is being raised

## Possible Solution
Modify line 106 in AlarmClock.js to support multiroom speaker setup. When having multiple speaker a list is generated by Sonos. The current code is likely based on one speaker setup

## Sample code or executed example
I replaced line 106 with:
let targetAlarm = result.Alarms.find((Alarms) => { return result.Alarms[0].ID === id })

but only as a quick fix due to the fact that I only have 1 active alarm in my setup

## Versions (and Environment)

**Node version**: 8.9.3
**node-sonos version**: 1.10.1
**OS**: Windows 10 for test, Linux om Raspberry PI in Prod

### PR DESCRIPTION
**Pull request by svrooij**
- `request` library replaced with `axios`
- PatchAlarm wasn't async
- PatchAlarm and SetAlarm now force the ID to be a string (as already specified in the documentation, fixes #413 
- Added GenerateCustomMetadata, fixes #330 
- Added multiple on-device tests (for settings alarms and playing notifications)
- Added relative volume adjustments
- Restore current position in queue and in the song after playing notification

### CODE REVIEW

**Comment by svrooij** [comment]
I'll keep adding improvements until you approve @bencevans 😉

**Comment by svrooij** [comment]
Did someone test my version out? Or does anybody have objections in accepting this PR?

**Comment by bencevans** [comment]
@svrooij shall give it a spin later today :smile_cat:

**Pull request merged**
