### PR TITLE
refactor: replace request-promise-native with axios

### PR DESCRIPTION
**Pull request by ChristianKohler**
First I would like to thank you. Great library.

I have a use case where I would like to use the library in a web project which is not possible at the moment due to multiple native dependencies. 

This PR replaces the native http request with axios, a node/browser http request library. Has not much effect on bundle size (<5kb gzipped).

### CODE REVIEW

**Comment by ChristianKohler** [comment]
Hi @svrooij 

Actually my use case would be React Native. There I would not have to handle cors.

https://facebook.github.io/react-native/docs/network#using-other-networking-libraries

> The security model for XMLHttpRequest is different than on web as there is no concept of CORS in native apps.

Question is if you want to go down this way? This PR was just an easy one to start with. I would create additional PRs while I try to get the library running with React Native. I will do it anyway so I though it might help someone else.

**Comment by bencevans** [comment]
`node-fetch` only works in node thus requires https://github.com/matthew-andrews/isomorphic-fetch or equivalent. I've used `axios` a lot more in recent projects as it's a simple to use api and "just works".

So long as whichever library we use returns the data in the same format (string, json etc.) we might be able to just drop in replace at these [locations](https://github.com/bencevans/node-sonos/search?q=%22const+request+%3D%22&unscoped_q=%22const+request+%3D%22). It appears a few instances have been missed thus far in your PR @ChristianKohler.

I love the idea of react-native projects having the ability to drop in the library so long as there isn't much (ideally any) overhead in maintaining the support.

Also I prefer the variable be kept as `request` I think as anyone reading the code who isn't aware exactly of what the `axios` module is, then it's represented better for readability but open to others opinion too. @svrooij

**Comment by ChristianKohler** [comment]
@svrooij React native runs in a js vm, not in a browser. Fetch is available there. So Isomorphic-fetch would work as well.

So using isomorphic-fetch instead of axios would also be an option. What I like about axios is that it does not define fetch as a global. But I would be happy with both approaches. 

I don't think it is a big change. It's actually only a few lines of code. I was able to get it running in a React Native environment with only a few changes. 

@bencevans Sounds great. Good idea with keeping the request variable. Can do that. Or replace it with isomorphic-fetch.

@bencevans  What occurrences did I miss to refactor?

If you are ok with adding support for react native / electron please let me know so I can add the changes we discussed to this PR.

**Comment by bencevans** [comment]
@ChristianKohler apologies, my eyes must've been half shut still this morning - looks like you've got all of them. Other than changing the name of the variable back I'm happy :man_dancing:

**Comment by svrooij** [comment]
I agree with Ben about the name change, would like to see that reverted. Other people won't get it if they check the source.

Maybe even a `request_vs_axios.md` file in the docs folder describing the change and the reasons.

I understand the need for it now and if everything (including the on-site tests) still work I'm happy to accept this PR.

**Comment by mharj** [comment]
Fyi, cross-fetch (can be polyfilled) supports Node/Native and browsers. At least I have been already pushing this heavily to own modules/projects if http client is needed. And axios is no go for me as it's just extra wrapper in modern browsers where there native fetch is anyway working.

**Comment by freaktechnik** [comment]
Given that request is now deprecated, switching away from it may make even more sense?

**Comment by bencevans** [comment]
@freaktechnik definitely.

**Comment by svrooij** [comment]
Let me state that I was never against changing stuff. We want to get node-sonos even better.

As @bencevans said [here](https://github.com/bencevans/node-sonos/pull/397#issuecomment-460593565) we would like it still to have the *request* variable name because that seems more clear.

When that is changed I'm happy to accept this change.

**Comment by svrooij** [comment]
According to [this page](https://blog.bitsrc.io/comparing-http-request-libraries-for-2019-7bedb1089c83) we have a few options to do requests. Axios seems to be the best choice.

Shall I migrate it, I’m working on some other small fixes at the moment, so could take this with it.
@bencevans @ChristianKohler ??

**Comment by bencevans** [comment]
@svrooij that'd be grand. Yes please!

**Comment by ChristianKohler** [comment]
The PR already uses axios. So I think the only thing we would have to change is using the request variable.

**Comment by svrooij** [comment]
@ChristianKohler I was already on some other branch. So this change is also in #414 

Closing this PR for now (because the changes are in the other PR as well.

**Pull request closed without merging**
