### PR TITLE
Alarm stuff

### LINKED ISSUE #160: Alarm Clock Control
Hi,

there are no instructions how to use the AlarmClock in API.md

Maybe someone can post instructions for Create, Update and Delete Alarm.

thx

### PR DESCRIPTION
**Pull request by svrooij**
Done some work on the alarm service, it is now available in the main library.
```node 
var alarmService = sonos.alarmClockService()
```

- [x] Delete alarm
- [x] List alarms
- [x] Patch alarm
- [x] Enable or disable an alarm
- [x] Create alarm (this will be hard....)
- [x] Update alarm
- [x] ~~the rest in the alarm class~~ ,tell me what you want to use

Fixes #160 hope you like it

### CODE REVIEW

**Comment by ebaauw** [comment]
Thank you very much, @svrooij, also for your other PRs.  This will save me a lot of low-level coding in homebridge-zp.

**Comment by bencevans** [comment]
Wonderfull! :smile_cat:  I'm back at university, Sonosless... as this is new functionality and the code looks grand I'm happy to merge. If there are changes to preexisting code/functionality I propose we get someone else from the community to run it and report back too before a merge? @ebaauw would you be up for playing with anything new coming in?

**Comment by ebaauw** [comment]
I updated the dependency in homebridge-zp to sonos@2.21.0 the other day and haven't yet found anything broken.  Of course, the proof of the pudding will be using the new main library services instead of my own hacks.  From what I've seen so far, I don't expect too many problems.

I do make heavy use of subscriptions, also for the alarm service - I don't think I ever query the zone players after the initial network topology discovery.  Maybe that's an area where we can improve?  Apart from en/disabling existing alarms from HomeKit, I haven't done much with alarms, though.

**Comment by svrooij** [comment]
So what you're saying is that you would like to see all the other events as well? Was thinking about it and that shouldn't be very hard.

But because for most things you only need one subscription was wondering how to do that. You don't need Alarm changed from every sonos because it will fire on every sonos. Same for topology changes. Was thinking about a singleton for this but that doesn't seem like a good idea in javascript

Or maybe just a start listening on the sonos class where you can specify where to listen for instead of only track, state and volume.

@ebaauw could you create a new issue for this?

The question @bencevans was asking was that he doesn't have access to a sonos speaker so he needs someone else to approve the pull requests for now.

**Comment by ebaauw** [comment]
> So what you're saying is that you would like to see all the other events as well? Was thinking about it and that shouldn't be very hard.

Currently I'm subscribing to events from `GroupManagement`, `MediaRenderer/AVTransport`, `MediaRenderer/GroupRenderingControl`, `MediaRenderer/RenderingControl` and `AlarmClock`.  `ZoneGroupTopology` events are on my backlog, but the current design of homebridge-zp cannot dynamically add or remove HomeKit accessories, so I cannot do anything with these.

> You don't need Alarm changed from every sonos because it will fire on every sonos.

Yes, that's a bit redundant.  However, subscribing to each zone player is easier than switching subscriptions when the player you're subscribed to shuts down.  I simply discard the event when I already received this `AlarmListVersion`.

> Same for topology changes.

Worse: you won't even get an event when the zone player you're subscribed to loses power or crashes.

> Or maybe just a start listening on the sonos class where you can specify where to listen for instead of only track, state and volume.

The way I've implemented it, I create a single listener and subsequently do a subscribe per service per zone player.  The listener parses the event, figures out which zone player and service it came from and then issues (the equivalent of) an `player.emit(serviceName)`, where `player` is an instance of `sonos`.

> could you create a new issue for this?

#205

> The question @bencevans was asking was that he doesn't have access to a sonos speaker so he needs someone else to approve the pull requests for now.

Sorry, I didn't catch that, but yeah, I could have a look.  Will have to wait till this weekend, though.  
Being Sonos-less must suck, my sympathies.

**Comment by ebaauw** [comment]
> It didn't had any options

Checking `/xml/AlarmClock1.xml` on my PlayBar, you're right!  I'll change homebridge-zp.

```xml
<action>
  <name>ListAlarms</name>
  <argumentList>
    <argument>
      <name>CurrentAlarmList</name>
      <direction>out</direction>
      <relatedStateVariable>A_ARG_TYPE_AlarmList</relatedStateVariable>
    </argument>
    <argument>
    <name>CurrentAlarmListVersion</name>
      <direction>out</direction>
      <relatedStateVariable>AlarmListVersion</relatedStateVariable>
    </argument>
  </argumentList>
</action>
```

**Pull request merged**
