### PR TITLE
Bug bashing

### PR DESCRIPTION
**Pull request by svrooij**
Tried to fix a lot of currently open issues.

Be sure to test before releasing. I'm not really sure about the error handling in the service file.
This was suggested by @hklages  in #448

### CODE REVIEW

**Comment by svrooij** [comment]
@bencevans I think you need to be the person to review this PR.

**Comment by bencevans** [comment]
Looks good to me but unable to test as don't have access to my Sonos system and likely won't be for a few months. Shall approve and leave it up to you if you would like to get someone else to test our continue in merging. Hope you're well in these crazy times!

**Comment by svrooij** [comment]
Could you test this out @hklages
Or someone else?

I don't want to make it instable by sometimes emitting a better error.

**Comment by hklages** [comment]
I am not experienced enough in NodeJS/Javascript/node-sonos. That's why I pointed you to the issue and suggested how to fix. As this change is in one of the most used parts of your package I suggest either to really test it thoroughly or to postpone the change.

**Pull request merged**
