### PR TITLE
queueSpotify() Implementation

### PR DESCRIPTION
**Pull request by stephen**
(Work in progress)

This needs to be tested by multiple parties before merging.. pulled in code from issue #24 and made some modifications.

In particular, I'm not sure where that "random" number comes from - on my system, it uses the same number (```10030020```) every time.

Todo:
- [ ] Output needs to be sanitized
- [ ] Linting problems
- [ ] Generalize for ```queueNext()```

Sample output:
```
$ SONOS_HOST=172.17.105.103 node examples/playspotify.js
null [ { '$': { 'xmlns:u': 'urn:schemas-upnp-org:service:AVTransport:1' },
    FirstTrackNumberEnqueued: [ '45' ],
    NumTracksAdded: [ '1' ],
    NewQueueLength: [ '45' ] } ]
```

### CODE REVIEW

**Comment by milkisevil** [comment]
What's the deal with this PR? 
Did it ever work? 
Is it dead? 
Has #23 superseded it?

On a slight tangent, I noticed that the ruby project [soffes/sonos](https://github.com/soffes/sonos) supports spotify queueing. See [`add_spotify_to_queue` method](https://github.com/soffes/sonos/blob/4c0b97114c8649dede27e66ebed46066c9548eb1/lib/sonos/endpoint/a_v_transport.rb#L132).

**Comment by bencevans** [comment]
I don't think anyone's working on it at the moment but would happily accept a pull-request!

**Comment by antxxxx** [comment]
I have amended the queueNext function so you can pass in metadata to it which allows you to add spotify tracks. This is in https://github.com/bencevans/node-sonos/pull/85
The hard part for adding spotify tracks is working out the metadata to put in there
If you have a look at https://github.com/antxxxx/node-sonos/tree/searchSpotify I have added a searchSpotify function which returns the metadata. Unfortunately, it calls out to a  new secure web API I created which then calls out to spotify webservice using soap and returns the data so I dont think this should be merged yet. It could probably be rewritten to call the spotify web service directly (its a soap service that uses smapi wsdl)

**Comment by bencevans** [comment]
`addSpotify` added by PR https://github.com/bencevans/node-sonos/pull/89/files. Function name subject to change before next release though. Play with git master/1.x if you want some experimentals!

**Comment by bencevans** [comment]
Superseded by https://github.com/bencevans/node-sonos/pull/126

**Pull request closed without merging**
