### PR TITLE
method to queue up next and use in addSpotify

### PR DESCRIPTION
**Pull request by ryanjohnstone**
Created this as queueNext didn't seem to do as I expected, i.e add a song next in the currently playing queue. I created a separate method as I didn't want to break the existing tests. 

I brought back the current position in the queue with currentTrack that way I could use queue to queue up a song in the position after that.

### CODE REVIEW

**Comment by bencevans** [comment]
Thanks @ryanjohnstone. I have briefly thought about this before however not actioned anything.

My thinking was if `queue`/`queueNext` accepted a Spotify URI e.g `'spotify:track:2Wr7zFf78V0EghGjGKhoP0`', then this could be identified within the appropriate function and added to the appropriate place in the queue.

I think effectively what you've done is the same but by writing a new function with a very similar name that may cause confusion.

What do you think to this approach? Would it solve your requirements?

**Comment by ryanjohnstone** [comment]
That sounds good and I was worried about adding the extra method that could cause confusion, I guess I just wanted to see what your thoughts were first. My main issue is that queueNext doesn't work the way I thought it would given its name. This method could replace the current queueNext but that breaks a few tests and my JS knowledge isn't at a part where I could understand what they were doing in a way to change them and still have them be useful to you.

**Comment by htilly** [comment]
What is the status of this one?! This is exactly what Im looking for =)
Trying to add a URL with an MP3 to an existing Spotify list.  
**Sonos.prototype.queueNext** throws me a error 500 but **Sonos.prototype.queueUpNext** do exactly what I want!

Please include this function!

BR
Tilly

**Comment by svrooij** [comment]
@ryanjohnstone I just fixed a lot of spotify issues in https://github.com/bencevans/node-sonos/pull/200 could you check if my assumption "That your pull-request is no longer necessary" is correct?

**Pull request closed without merging**
