### PR TITLE
Playtuneinradio

### PR DESCRIPTION
**Pull request by sseiber**
This PR includes an api for playing a Tunein radio station.
The new api is:

```
sonos.playTuneinRadio(stationId, stationTitle, callback)
```

The `stationId` is the Tunein radio provisioned station id. You will need to get this from Tunein radio (e.g. try a web search against the tuneinradio.com domain). Once found this station id will direct the Sonos system to start streaming audio from that station.

The `stationTitle` is the string used in the Sonos UI as the title to the radio station.

### CODE REVIEW

**Comment by sseiber** [comment]
Hi @bencevans @stephen @mrose17,

`https://github.com/bencevans/node-sonos/pull/154`

This PR adds Tunein radio support. Please have a look.

**Comment by mrose17** [comment]
@bencevans & @stephen - my inclination is to merge. if i don't hear anything from either of you saying "STOP", my game plan is to merge tomorrow, tuesday, january 9, at 10:00AM us/pt.  thanks!

ps: no offense taken if someone says "STOP"

**Comment by bencevans** [comment]
No need to wait for us :)

**Comment by mrose17** [comment]
now available via npm as 0.14.1

**Pull request merged**
