### PR TITLE
Tests and Examples for playing Spotify URIs

### PR DESCRIPTION
**Pull request by sseiber**

### CODE REVIEW

**Comment by sseiber** [comment]
@bencevans Here's a PR for the tests and examples for playing Spotify URIs

**Comment by sseiber** [comment]
Also @bencevans it looks like the package version should be bumped (for the Spotify features) and new version uploaded to npmjs.

**Comment by bencevans** [comment]
Cheers. I've just tried it out but getting 500 errors on the playWithSpotify example following 

```diff
diff --git a/examples/playSpotifyMusic.js b/examples/playSpotifyMusic.js
index e446bd9..dd0ccf0 100644
--- a/examples/playSpotifyMusic.js
+++ b/examples/playSpotifyMusic.js
@@ -20,7 +20,7 @@ var sonos = new Sonos(process.env.SONOS_HOST || '192.168.2.11')
 
 var spotifyUri = 'spotify:track:1AhDOtG9vPSOmsWgNW0BEY'
 
-this.sonos.play(spotifyUri, (err, result) => {
+sonos.play(spotifyUri, (err, result) => {
   if (err) {
     return console.log(err)
   }
```

Are you able to run it successfully?

**Comment by sseiber** [comment]
@bencevans I copied the template from the other examples, namely the line:
```
var sonos = new Sonos(process.env.SONOS_HOST || '192.168.2.11')
```
But obviously these are network/installation dependent. I'm able to successfully call sonos.play api if I first execute a search on my network for sonos controllers. E.g.:
```
search.on('DeviceAvailable', (device, model) => {
  device.getZoneAttrs((err, deviceAttrs) => {
    // get the zone here
  });
});
```

**Comment by sseiber** [comment]
Ah, and yes the "this." should be removed from the play api example -- my mistake.

**Comment by bencevans** [comment]
Hmm I'm in the middle of some heavy uni workload at the moment so can't dedicate much time unfortunately. When I tried it out I set SONOS_HOST to the IP of a SONOS PLAY:5 (Gen 1) device and hit the issue. I'll look into it further but 'fraid it won't be for a couple of weeks.

**Pull request merged**
