### PR TITLE
Fixing Bass and Treble setters in RenderingControl

### PR DESCRIPTION
**Pull request by pascalopitz**
- Bass and treble just take value instead of forcing boolean
- Additional comments to explain values

### CODE REVIEW

**Comment by svrooij** [comment]
I manually pulled these changes to https://github.com/bencevans/node-sonos/tree/alpha
(as a first change to auto-release from the alpha branch).

Could you use the [commit message style](https://github.com/semantic-release/semantic-release#commit-message-format) needed for semantic release next time? That will make sure that when we pull your code it will automatically get released.

So, start with:

- `fix: [short description]` for small fixed (triggers a patch release)
- `feat: [short description]` for new features (triggers a minor release)

**Comment by pascalopitz** [comment]
Yes, totally ... do you want me to force push commit message updates?

**Comment by svrooij** [comment]
@pascalopitz the automated releases are all setup. The changes in this pr are already in the alpha branch (but not released because it didn’t pick up commit messages that should trigger a release. I’ll close this one (I merged it to alpha already as a test). Could you force push the others?

**Comment by pascalopitz** [comment]
Done.

**Comment by pascalopitz** [comment]
Confirmed it works on my [latest release](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/releases/tag/v0.2.1-alpha6), which is using the alpha package

**Pull request closed without merging**
