### PR TITLE
Allow the UDP discovery bind port to be specified

### PR DESCRIPTION
**Pull request by driskell**
Hello

This is another one for specifying port. This allows the options to contain a port that is passed to the datagram bind. Helps me configure my firewall 👍 

Thanks

### CODE REVIEW

**Comment by bencevans** [comment]
Lovely, cheers.

**Comment by driskell** [comment]
Is there any help you need to release a new version?

**Comment by bencevans** [comment]
@driskell sorry only just seen this. Thanks for all your contributions. If you're up for it we'd love to have you join the core maintainers.

I'm travelling here and there at the moment and don't have access to a Sonos network very often but would love to see the project maintained better. If you're interested let me know and I'll add you on!

**Comment by driskell** [comment]
Thanks @bencevans ! I don't think I will have much spare time to help much at the moment - I think I've spread myself a little thin the last few months. I think I'll be around again eventually though to improve some other bits and pieces and Spotify bits and maybe it would be worth it at that time if you're happy with some ideas.

**Comment by driskell** [comment]
Oh! One thing I want to look at eventually if you'd be happy - is to remove the discovery code and replace it with [node-ssdp](https://github.com/diversario/node-ssdp) - and have it load the device XML so we can access the manufacturer and version numbering :) Definitely a small useful thing for homebridge-sonos and maybe even contain something useful in future for detecting specific feature abilities

**Pull request merged**
