### PR TITLE
Typescript types

### LINKED ISSUE #512: Add types to node-sonos
Hello, I'm adding this issue to raise awareness about the desire of not only me, but I'm sure for others, for node-sonos.

Tbh i'm not personally very familiar with adding types to packages, but I might work on it.

Anyways if anyone else wants to, you can refer to this issue

(NOTE: I can't label this as a 'enhancement' or 'feature request'?)

### PR DESCRIPTION
**Pull request by svrooij**
I've managed to get started with generating Typescript definition files from existing Javascript code I followed [this manual](https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html).

This way everybody that likes to use the Sonos library can also enjoy the comfort of automatic documentation.

This PR includes a first version of the type definition. The types are also generated in the **prepack** stage, so they will never become outdated. 

Improving the type definition can be done by adding [jsdoc](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html) comments to the javascript code.

Check this sample

https://github.com/svrooij/node-sonos/blob/9a87007e3aa81886fca274ed301a64f3bb7ff2ab/lib/services/alarm-clock.service.js#L30-L45

Fixed #512 @realwakils 
What do you think @bencevans

### CODE REVIEW

**Comment by svrooij** [comment]
@pascalopitz can you check if you application still works with all these types now included. I've tried to not break anything and just including a first version of the types.

Installing with `npm install svrooij/node-sonos#feature/types --save` (I guess, never installed a package from git branch).

**Review by bencevans — APPROVED** [review]
LGTM

**Comment by pascalopitz** [comment]
@svrooij Nope, not looking good for me

image

**Comment by svrooij** [comment]
@pascalopitz The AsyncDeviceDiscovery is the only thing I've changed. A promise cannot return multiple arguments, so I changed it to return an object with `device` and `model`. The `model` was missing in the async version.

if you change [this](https://github.com/pascalopitz/unoffical-sonos-controller-for-linux/blob/df4c15955b8ba4cf600238c6cac251a4b33fc88b/src/ui/services/SonosService.js#L79-L84) to:

```js
    async searchForDevices(timeout = 1000) {
        const discovered = await new AsyncDeviceDiscovery().discover({
            timeout,
            port: SONOS_DISCOVERY_PORT,
        });
        await this.connectDevice(discovered.device);
    },
```

Related code:
https://github.com/bencevans/node-sonos/blob/bea996efa92b8519dc975596424f0c615dec6de7/lib/asyncDeviceDiscovery.js#L9-L21

**Comment by pascalopitz** [comment]
Confirmed. I just figured out the same ...

**Comment by svrooij** [comment]
> Confirmed. I just figured out the same ...

If you're facing any other issues with the new alpha, could you create a new issue?

**Pull request merged**
