### PR TITLE
Sonos now ES6 Class, additional getZPInfo method, additional services…

### PR DESCRIPTION
**Pull request by pascalopitz**
… shorthands

### CODE REVIEW

**Comment by svrooij** [comment]
How do we progress with this PR?

Is everything in de alpha branch still working and tested by anyone?

- @bencevans 
- @hklages could you please check if the [current alpha version](https://www.npmjs.com/package/sonos/v/1.14.0-alpha.3) is still working with your integrations?

After the alpha version is checked. We will release a new latest version, and then merge this as the new alpha. This PR has so manu changes that I think it's better to split the releases this way. Everybody agrees?

**Comment by pascalopitz** [comment]
Since we released 1.14.0, should this not be 1.14.1-alpha.1 ?

**Comment by svrooij** [comment]
Yes it should..... But I didn't push the new master te Alpha before I merged your PR.

So my mistake...

Can we automate that?
Push to master = rebase alpha (or similar)

**Comment by svrooij** [comment]
@pascalopitz or 1.15.0-alpha.1 because you made it a feature 😄 

This should be automated asap.
After push to master also update alpha, anybody knows which git command we need for that? Then I'll automate it with actions.

**Pull request merged**
