### PR TITLE
feat: add/delete playlist, add/remove songs to/from playlist

### PR DESCRIPTION
**Pull request by phoenixrising87**
Hi everyone,

I added some new functionality for creating playlists and also for deleting them.
Please have a look over it :-)

### CODE REVIEW

**Comment by svrooij** [comment]
Do you also have a way of how to find out the playlist id to delete a playlist?
How do you add stuff to the playlist? Or does it save the current queue as playlist?

**Comment by phoenixrising87** [comment]
> Do you also have a way of how to find out the playlist id to delete a playlist?
Yes, you can right get all the playlists with: 
https://github.com/bencevans/node-sonos/blob/master/examples/getsonosplaylists.js
The `uri` looks for example like this `file:///jffs/settings/savedqueues.rsq#9`. The number at the end, is the `id`.

> How do you add stuff to the playlist? Or does it save the current queue as playlist?
In here it is creating an empty list. I'm on it, to add also the functionality for adding songs to playlists.

**Comment by phoenixrising87** [comment]
I added the functionality for adding songs etc to the playlist. Removing songs is still on my plan.

**Comment by phoenixrising87** [comment]
Also removing songs is now possible

**Comment by phoenixrising87** [comment]
I would appreciate some reviews for using this integration in my application :)

**Pull request merged**
